"use client";

import { useMemo, useState } from "react";
import { UserRound } from "lucide-react";
import { CustomerFilters, type CustomerFilterValue } from "@/components/customers/CustomerFilters";
import { CustomerMetrics } from "@/components/customers/CustomerMetrics";
import { CustomerProfileDrawer } from "@/components/customers/CustomerProfileDrawer";
import { CustomerTable } from "@/components/customers/CustomerTable";
import { Sidebar } from "@/components/layout/Sidebar";
import { TopBar } from "@/components/layout/TopBar";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import { customerCountries, customers, type Customer } from "@/mock/customers";

const initialFilters: CustomerFilterValue = { query: "", country: "all", platform: "all", subscription: "all" };
export default function CustomersPage() { const [sidebarCollapsed, setSidebarCollapsed] = useState(false); const [mobileNavigationOpen, setMobileNavigationOpen] = useState(false); const [filters, setFilters] = useState(initialFilters); const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null); const filteredCustomers = useMemo(() => customers.filter((customer) => { const query = filters.query.toLowerCase(); const matchingQuery = !query || [customer.name, customer.email, customer.currentServer].some((value) => value.toLowerCase().includes(query)); return matchingQuery && (filters.country === "all" || customer.country === filters.country) && (filters.platform === "all" || customer.platform === filters.platform) && (filters.subscription === "all" || customer.subscription === filters.subscription); }), [filters]); return <div className="flex min-h-screen bg-[#0d1524] font-sans text-white"><Sidebar collapsed={sidebarCollapsed} onCollapsedChange={setSidebarCollapsed} activeItem="Customers" /><Sheet open={mobileNavigationOpen} onOpenChange={setMobileNavigationOpen}><SheetContent side="left" showCloseButton={false} className="w-72 border-white/8 bg-[#0b1220] p-0 sm:w-72 lg:hidden"><Sidebar collapsed={false} onCollapsedChange={setSidebarCollapsed} activeItem="Customers" mobile /></SheetContent></Sheet><div className="flex min-w-0 flex-1 flex-col"><TopBar onMenuClick={() => setMobileNavigationOpen(true)} /><main className="flex-1 px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div><p className="mb-2 text-sm font-medium text-blue-400">Customer operations</p><h1 className="flex items-center gap-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl"><UserRound className="size-6 text-blue-400" />Customer workspace</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Understand customer activity, subscription health, and support context before issues become tickets.</p></div><div className="mt-8"><CustomerMetrics /></div><section className="mt-5 rounded-xl border border-white/8 bg-[#111b2e] p-4 sm:p-5"><CustomerFilters value={filters} countries={customerCountries} onChange={setFilters} /><div className="mt-5 flex items-center justify-between"><p className="text-sm text-slate-400"><span className="font-medium text-slate-200">{filteredCustomers.length}</span> customers matched</p><p className="text-xs text-slate-500">Operational data · refreshed moments ago</p></div></section><section className="mt-5 overflow-hidden rounded-xl border border-white/8 bg-[#111b2e]"><CustomerTable customers={filteredCustomers} onOpenCustomer={setSelectedCustomer} /></section>{filteredCustomers.length === 0 && <p className="mt-5 rounded-xl border border-dashed border-white/10 p-12 text-center text-sm text-slate-500">No customers match these filters.</p>}</main></div><CustomerProfileDrawer customer={selectedCustomer} open={Boolean(selectedCustomer)} onOpenChange={(open) => { if (!open) setSelectedCustomer(null); }} /></div>; }
