"use client";

import { CreditCard, Crown, Link2, MapPin, MonitorSmartphone, UserRound } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { DeviceCard } from "@/components/customers/DeviceCard";
import { EmptyState, SessionTimeline } from "@/components/customers/SessionTimeline";
import { SubscriptionBadge } from "@/components/customers/SubscriptionBadge";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { Customer } from "@/mock/customers";

interface CustomerProfileDrawerProps { customer: Customer | null; open: boolean; onOpenChange: (open: boolean) => void; }
const eventIcons = { subscription: Crown, session: MonitorSmartphone, payment: CreditCard, referral: Link2 };

export function CustomerProfileDrawer({ customer, open, onOpenChange }: CustomerProfileDrawerProps) {
  if (!customer) return null;
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full gap-0 overflow-y-auto border-white/10 bg-[#111b2e] p-0 sm:max-w-2xl"><SheetHeader className="border-b border-white/8 p-5 pr-12"><div className="flex items-start gap-3"><Avatar size="lg"><AvatarFallback className="bg-blue-500/15 font-semibold text-blue-300">{customer.initials}</AvatarFallback></Avatar><div><SheetTitle className="text-white">{customer.name}</SheetTitle><SheetDescription className="mt-1">{customer.email}</SheetDescription><div className="mt-3 flex flex-wrap items-center gap-2"><SubscriptionBadge status={customer.subscription} /><span className="text-xs text-slate-500">{customer.plan}</span></div></div></div></SheetHeader><Tabs defaultValue="overview" className="gap-0"><div className="overflow-x-auto border-b border-white/8 px-5"><TabsList variant="line" className="h-10 min-w-max gap-3"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="devices">Devices</TabsTrigger><TabsTrigger value="sessions">Sessions</TabsTrigger><TabsTrigger value="subscription">Subscription</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger></TabsList></div><div className="p-5"><TabsContent value="overview"><Overview customer={customer} /></TabsContent><TabsContent value="devices"><div className="grid gap-3 sm:grid-cols-2">{customer.devices.map((device) => <DeviceCard key={device.id} device={device} />)}</div></TabsContent><TabsContent value="sessions"><SessionTimeline sessions={customer.sessions} /></TabsContent><TabsContent value="subscription"><Subscription customer={customer} /></TabsContent><TabsContent value="payments"><Payments customer={customer} /></TabsContent><TabsContent value="timeline"><Timeline customer={customer} /></TabsContent></div></Tabs></SheetContent></Sheet>;
}

function Overview({ customer }: { customer: Customer }) { return <div className="grid gap-4 sm:grid-cols-2"><Info icon={MapPin} label="Country" value={customer.country} /><Info icon={MonitorSmartphone} label="Current server" value={customer.currentServer} /><Info icon={UserRound} label="Lifetime revenue" value={customer.lifetimeRevenue} /><Info icon={Link2} label="Referral status" value={customer.referralStatus} /><div className="rounded-xl border border-white/8 bg-white/[0.025] p-4 sm:col-span-2"><p className="text-xs font-medium text-slate-500">Operational context</p><p className="mt-2 text-sm leading-6 text-slate-300">Last active {customer.lastActive} on {customer.platform}. {customer.devices.length} registered {customer.devices.length === 1 ? "device" : "devices"} and {customer.sessions.length} recent session{customer.sessions.length === 1 ? "" : "s"} are available for review.</p></div></div>; }
function Info({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="rounded-xl border border-white/8 bg-white/[0.025] p-4"><Icon className="size-4 text-blue-400" /><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-slate-200">{value}</p></div>; }
function Subscription({ customer }: { customer: Customer }) { return <div className="space-y-3"><Detail label="Plan" value={customer.plan} /><Detail label="Status" value={<SubscriptionBadge status={customer.subscription} />} /><Detail label="Renews / expires" value={customer.expiry} /><Detail label="Current server" value={customer.currentServer} /></div>; }
function Detail({ label, value }: { label: string; value: React.ReactNode }) { return <div className="flex items-center justify-between rounded-lg border border-white/8 bg-white/[0.025] px-4 py-3"><span className="text-sm text-slate-500">{label}</span><span className="text-sm font-medium text-slate-200">{value}</span></div>; }
function Payments({ customer }: { customer: Customer }) { if (!customer.payments.length) return <EmptyState message="No payment activity recorded for this customer." />; return <div className="space-y-3">{customer.payments.map((payment) => <div key={payment.id} className="flex items-center justify-between rounded-lg border border-white/8 bg-white/[0.025] p-3"><div><p className="text-sm font-medium text-slate-200">{payment.amount} · {payment.status}</p><p className="mt-1 text-xs text-slate-500">{payment.date} · {payment.method}</p></div><CreditCard className="size-4 text-slate-500" /></div>)}</div>; }
function Timeline({ customer }: { customer: Customer }) { return <div className="space-y-4">{customer.timeline.map((event) => { const Icon = eventIcons[event.type]; return <div key={event.title} className="flex gap-3"><div className="mt-0.5 rounded-lg bg-blue-500/10 p-2 text-blue-400"><Icon className="size-3.5" /></div><div><div className="flex items-center gap-2"><p className="text-sm font-medium text-slate-200">{event.title}</p><span className="text-xs text-slate-500">{event.time}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{event.detail}</p></div></div>; })}</div>; }
